# Generated by Django 5.0.3 on 2024-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_publisher_recommendedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_authors', related_query_name='followed_authors', to='book.user'),
        ),
    ]
