# Generated by Django 5.0.3 on 2024-03-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='book.author'),
        ),
    ]
